#pragma once
// AUTO-GENERATED by scripts/gen_daycare_data.py — DO NOT EDIT
// Source: PokeAPI (pokeapi.co)

#include <stdint.h>
#include <stddef.h>

// ── Pokemon types ─────────────────────────────────────────────────────────
enum PkmnType : uint8_t {
    TYPE_NORMAL = 0,
    TYPE_FIGHTING = 1,
    TYPE_FLYING = 2,
    TYPE_POISON = 3,
    TYPE_GROUND = 4,
    TYPE_ROCK = 5,
    TYPE_BUG = 6,
    TYPE_GHOST = 7,
    TYPE_FIRE = 8,
    TYPE_WATER = 9,
    TYPE_GRASS = 10,
    TYPE_ELECTRIC = 11,
    TYPE_PSYCHIC = 12,
    TYPE_ICE = 13,
    TYPE_DRAGON = 14,
    TYPE_COUNT = 15
};

enum PkmnHabitat : uint8_t {
    HABITAT_CAVE = 0,
    HABITAT_FOREST = 1,
    HABITAT_GRASSLAND = 2,
    HABITAT_MOUNTAIN = 3,
    HABITAT_RARE = 4,
    HABITAT_ROUGH_TERRAIN = 5,
    HABITAT_SEA = 6,
    HABITAT_URBAN = 7,
    HABITAT_WATERS_EDGE = 8,
    HABITAT_COUNT = 9
};

enum PkmnPersonality : uint8_t {
    PERS_PROUD = 0,
    PERS_CLUMSY = 1,
    PERS_AGGRESSIVE = 2,
    PERS_GENTLE = 3,
    PERS_SNEAKY = 4,
    PERS_LAZY = 5,
    PERS_ANXIOUS = 6,
    PERS_COUNT = 7
};

enum StatBias : uint8_t {
    BIAS_HP = 0, BIAS_ATK = 1, BIAS_DEF = 2, BIAS_SPA = 3, BIAS_SPD = 4
};

// ── Species profile ───────────────────────────────────────────────────────
struct DaycareSpecies {
    uint8_t dexNum;
    uint8_t type1;
    uint8_t type2;
    uint8_t habitat;
    uint8_t statBias;
    uint8_t personality;
    uint8_t evoStage;
    uint8_t moveCount;
    uint8_t moves[15];
    uint8_t flavorIdx;     // index into daycareFlavorFragments[]
};

// ── Gen 1 move names (165 moves) ───────────────────────────────────────────
static const char *const daycareMoveNames[] = {
    "???",  // 0 (unused)
    "Pound",  // 1
    "Karate Chop",  // 2
    "Double Slap",  // 3
    "Comet Punch",  // 4
    "Mega Punch",  // 5
    "Pay Day",  // 6
    "Fire Punch",  // 7
    "Ice Punch",  // 8
    "Thunder Punch",  // 9
    "Scratch",  // 10
    "Vice Grip",  // 11
    "Guillotine",  // 12
    "Razor Wind",  // 13
    "Swords Dance",  // 14
    "Cut",  // 15
    "Gust",  // 16
    "Wing Attack",  // 17
    "Whirlwind",  // 18
    "Fly",  // 19
    "Bind",  // 20
    "Slam",  // 21
    "Vine Whip",  // 22
    "Stomp",  // 23
    "Double Kick",  // 24
    "Mega Kick",  // 25
    "Jump Kick",  // 26
    "Rolling Kick",  // 27
    "Sand Attack",  // 28
    "Headbutt",  // 29
    "Horn Attack",  // 30
    "Fury Attack",  // 31
    "Horn Drill",  // 32
    "Tackle",  // 33
    "Body Slam",  // 34
    "Wrap",  // 35
    "Take Down",  // 36
    "Thrash",  // 37
    "Double Edge",  // 38
    "Tail Whip",  // 39
    "Poison Sting",  // 40
    "Twineedle",  // 41
    "Pin Missile",  // 42
    "Leer",  // 43
    "Bite",  // 44
    "Growl",  // 45
    "Roar",  // 46
    "Sing",  // 47
    "Supersonic",  // 48
    "Sonic Boom",  // 49
    "Disable",  // 50
    "Acid",  // 51
    "Ember",  // 52
    "Flamethrower",  // 53
    "Mist",  // 54
    "Water Gun",  // 55
    "Hydro Pump",  // 56
    "Surf",  // 57
    "Ice Beam",  // 58
    "Blizzard",  // 59
    "Psybeam",  // 60
    "Bubble Beam",  // 61
    "Aurora Beam",  // 62
    "Hyper Beam",  // 63
    "Peck",  // 64
    "Drill Peck",  // 65
    "Submission",  // 66
    "Low Kick",  // 67
    "Counter",  // 68
    "Seismic Toss",  // 69
    "Strength",  // 70
    "Absorb",  // 71
    "Mega Drain",  // 72
    "Leech Seed",  // 73
    "Growth",  // 74
    "Razor Leaf",  // 75
    "Solar Beam",  // 76
    "Poison Powder",  // 77
    "Stun Spore",  // 78
    "Sleep Powder",  // 79
    "Petal Dance",  // 80
    "String Shot",  // 81
    "Dragon Rage",  // 82
    "Fire Spin",  // 83
    "Thunder Shock",  // 84
    "Thunderbolt",  // 85
    "Thunder Wave",  // 86
    "Thunder",  // 87
    "Rock Throw",  // 88
    "Earthquake",  // 89
    "Fissure",  // 90
    "Dig",  // 91
    "Toxic",  // 92
    "Confusion",  // 93
    "Psychic",  // 94
    "Hypnosis",  // 95
    "Meditate",  // 96
    "Agility",  // 97
    "Quick Attack",  // 98
    "Rage",  // 99
    "Teleport",  // 100
    "Night Shade",  // 101
    "Mimic",  // 102
    "Screech",  // 103
    "Double Team",  // 104
    "Recover",  // 105
    "Harden",  // 106
    "Minimize",  // 107
    "Smokescreen",  // 108
    "Confuse Ray",  // 109
    "Withdraw",  // 110
    "Defense Curl",  // 111
    "Barrier",  // 112
    "Light Screen",  // 113
    "Haze",  // 114
    "Reflect",  // 115
    "Focus Energy",  // 116
    "Bide",  // 117
    "Metronome",  // 118
    "Mirror Move",  // 119
    "Self Destruct",  // 120
    "Egg Bomb",  // 121
    "Lick",  // 122
    "Smog",  // 123
    "Sludge",  // 124
    "Bone Club",  // 125
    "Fire Blast",  // 126
    "Waterfall",  // 127
    "Clamp",  // 128
    "Swift",  // 129
    "Skull Bash",  // 130
    "Spike Cannon",  // 131
    "Constrict",  // 132
    "Amnesia",  // 133
    "Kinesis",  // 134
    "Soft Boiled",  // 135
    "High Jump Kick",  // 136
    "Glare",  // 137
    "Dream Eater",  // 138
    "Poison Gas",  // 139
    "Barrage",  // 140
    "Leech Life",  // 141
    "Lovely Kiss",  // 142
    "Sky Attack",  // 143
    "Transform",  // 144
    "Bubble",  // 145
    "Dizzy Punch",  // 146
    "Spore",  // 147
    "Flash",  // 148
    "Psywave",  // 149
    "Splash",  // 150
    "Acid Armor",  // 151
    "Crabhammer",  // 152
    "Explosion",  // 153
    "Fury Swipes",  // 154
    "Bonemerang",  // 155
    "Rest",  // 156
    "Rock Slide",  // 157
    "Hyper Fang",  // 158
    "Sharpen",  // 159
    "Conversion",  // 160
    "Tri Attack",  // 161
    "Super Fang",  // 162
    "Slash",  // 163
    "Substitute",  // 164
    "Struggle",  // 165
};
static constexpr uint8_t DAYCARE_MOVE_COUNT = 165;

// ── Species display names (Pokedex order 1-151) ─────────────────────────
static const char *const daycareSpeciesNames[] = {
    "???",  // 0 (unused)
    "Bulbasaur",  // 1
    "Ivysaur",  // 2
    "Venusaur",  // 3
    "Charmander",  // 4
    "Charmeleon",  // 5
    "Charizard",  // 6
    "Squirtle",  // 7
    "Wartortle",  // 8
    "Blastoise",  // 9
    "Caterpie",  // 10
    "Metapod",  // 11
    "Butterfree",  // 12
    "Weedle",  // 13
    "Kakuna",  // 14
    "Beedrill",  // 15
    "Pidgey",  // 16
    "Pidgeotto",  // 17
    "Pidgeot",  // 18
    "Rattata",  // 19
    "Raticate",  // 20
    "Spearow",  // 21
    "Fearow",  // 22
    "Ekans",  // 23
    "Arbok",  // 24
    "Pikachu",  // 25
    "Raichu",  // 26
    "Sandshrew",  // 27
    "Sandslash",  // 28
    "Nidoran F",  // 29
    "Nidorina",  // 30
    "Nidoqueen",  // 31
    "Nidoran M",  // 32
    "Nidorino",  // 33
    "Nidoking",  // 34
    "Clefairy",  // 35
    "Clefable",  // 36
    "Vulpix",  // 37
    "Ninetales",  // 38
    "Jigglypuff",  // 39
    "Wigglytuff",  // 40
    "Zubat",  // 41
    "Golbat",  // 42
    "Oddish",  // 43
    "Gloom",  // 44
    "Vileplume",  // 45
    "Paras",  // 46
    "Parasect",  // 47
    "Venonat",  // 48
    "Venomoth",  // 49
    "Diglett",  // 50
    "Dugtrio",  // 51
    "Meowth",  // 52
    "Persian",  // 53
    "Psyduck",  // 54
    "Golduck",  // 55
    "Mankey",  // 56
    "Primeape",  // 57
    "Growlithe",  // 58
    "Arcanine",  // 59
    "Poliwag",  // 60
    "Poliwhirl",  // 61
    "Poliwrath",  // 62
    "Abra",  // 63
    "Kadabra",  // 64
    "Alakazam",  // 65
    "Machop",  // 66
    "Machoke",  // 67
    "Machamp",  // 68
    "Bellsprout",  // 69
    "Weepinbell",  // 70
    "Victreebel",  // 71
    "Tentacool",  // 72
    "Tentacruel",  // 73
    "Geodude",  // 74
    "Graveler",  // 75
    "Golem",  // 76
    "Ponyta",  // 77
    "Rapidash",  // 78
    "Slowpoke",  // 79
    "Slowbro",  // 80
    "Magnemite",  // 81
    "Magneton",  // 82
    "Farfetch'd",  // 83
    "Doduo",  // 84
    "Dodrio",  // 85
    "Seel",  // 86
    "Dewgong",  // 87
    "Grimer",  // 88
    "Muk",  // 89
    "Shellder",  // 90
    "Cloyster",  // 91
    "Gastly",  // 92
    "Haunter",  // 93
    "Gengar",  // 94
    "Onix",  // 95
    "Drowzee",  // 96
    "Hypno",  // 97
    "Krabby",  // 98
    "Kingler",  // 99
    "Voltorb",  // 100
    "Electrode",  // 101
    "Exeggcute",  // 102
    "Exeggutor",  // 103
    "Cubone",  // 104
    "Marowak",  // 105
    "Hitmonlee",  // 106
    "Hitmonchan",  // 107
    "Lickitung",  // 108
    "Koffing",  // 109
    "Weezing",  // 110
    "Rhyhorn",  // 111
    "Rhydon",  // 112
    "Chansey",  // 113
    "Tangela",  // 114
    "Kangaskhan",  // 115
    "Horsea",  // 116
    "Seadra",  // 117
    "Goldeen",  // 118
    "Seaking",  // 119
    "Staryu",  // 120
    "Starmie",  // 121
    "Mr. Mime",  // 122
    "Scyther",  // 123
    "Jynx",  // 124
    "Electabuzz",  // 125
    "Magmar",  // 126
    "Pinsir",  // 127
    "Tauros",  // 128
    "Magikarp",  // 129
    "Gyarados",  // 130
    "Lapras",  // 131
    "Ditto",  // 132
    "Eevee",  // 133
    "Vaporeon",  // 134
    "Jolteon",  // 135
    "Flareon",  // 136
    "Porygon",  // 137
    "Omanyte",  // 138
    "Omastar",  // 139
    "Kabuto",  // 140
    "Kabutops",  // 141
    "Aerodactyl",  // 142
    "Snorlax",  // 143
    "Articuno",  // 144
    "Zapdos",  // 145
    "Moltres",  // 146
    "Dratini",  // 147
    "Dragonair",  // 148
    "Dragonite",  // 149
    "Mewtwo",  // 150
    "Mew",  // 151
};

// ── Flavor fragments (keywords from Pokedex entries) ────────────────────
static const char *const daycareFlavorFragments[] = {
    "strange|seed|planted|back|birth",  // 0: Bulbasaur
    "bulb|back|grows|large|appears",  // 1: Ivysaur
    "plant|blooms|absorbing|solar|energy",  // 2: Venusaur
    "obviously|prefers|places|rains|steam",  // 3: Charmander
    "swings|burning|tail|elevates|temperature",  // 4: Charmeleon
    "spits|fire|enough|melt|boulders",  // 5: Charizard
    "after|birth|back|swells|hardens",  // 6: Squirtle
    "often|hides|water|stalk|unwary",  // 7: Wartortle
    "brutal|pressurized|water|jets|shell",  // 8: Blastoise
    "short|feet|tipped|suction|pads",  // 9: Caterpie
    "vulnerable|attack|while|shell|soft",  // 10: Metapod
    "battle|flaps|wings|high|speed",  // 11: Butterfree
    "often|found|forests|eating|leaves",  // 12: Weedle
    "almost|incapable|moving|only|harden",  // 13: Kakuna
    "flies|high|speed|attacks|using",  // 14: Beedrill
    "common|sight|forests|woods|flaps",  // 15: Pidgey
    "protective|sprawling|territorial|area|fiercely",  // 16: Pidgeotto
    "hunting|skims|surface|water|high",  // 17: Pidgeot
    "bites|anything|attacks|small|quick",  // 18: Rattata
    "uses|whis|kers|maintain|balance",  // 19: Raticate
    "eats|bugs|grassy|areas|flap",  // 20: Spearow
    "huge|magnificent|wings|keep|aloft",  // 21: Fearow
    "moves|silently|stealthily|eats|eggs",  // 22: Ekans
    "rumored|ferocious|warning|markings|belly",  // 23: Arbok
    "several|these|gather|electricity|could",  // 24: Pikachu
    "long|tail|serves|ground|protect",  // 25: Raichu
    "burrows|deep|underground|arid|locations",  // 26: Sandshrew
    "curls|into|spiny|ball|threatened",  // 27: Sandslash
    "although|small|venomous|barbs|render",  // 28: Nidoran F
    "female|horn|develops|slowly|prefers",  // 29: Nidorina
    "hard|scales|provide|strong|protection",  // 30: Nidoqueen
    "stiffens|ears|sense|danger|larger",  // 31: Nidoran M
    "aggressive|quick|attack|horn|head",  // 32: Nidorino
    "uses|powerful|tail|battle|smash",  // 33: Nidoking
    "magical|cute|appeal|many|admirers",  // 34: Clefairy
    "timid|fairy|rarely|seen|hide",  // 35: Clefable
    "time|birth|just|tail|splits",  // 36: Vulpix
    "smart|vengeful|grabbing|many|tails",  // 37: Ninetales
    "huge|eyes|light|sings|mysteriously",  // 38: Jigglypuff
    "body|soft|rubbery|angered|suck",  // 39: Wigglytuff
    "forms|colonies|perpetually|dark|places",  // 40: Zubat
    "once|strikes|stop|draining|energy",  // 41: Golbat
    "during|keeps|face|buried|ground",  // 42: Oddish
    "fluid|oozes|mouth|drool|nectar",  // 43: Gloom
    "larger|petals|more|toxic|pollen",  // 44: Vileplume
    "burrows|suck|tree|roots|mushrooms",  // 45: Paras
    "host|parasite|pair|mushroom|taken",  // 46: Parasect
    "lives|shadows|tall|trees|where",  // 47: Venonat
    "dust|like|scales|covering|wings",  // 48: Venomoth
    "lives|yard|underground|where|feeds",  // 49: Diglett
    "team|diglett|triplets|triggers|huge",  // 50: Dugtrio
    "adores|circular|objects|wanders|streets",  // 51: Meowth
    "although|many|admirers|tough|raise",  // 52: Persian
    "while|lulling|enemies|vacant|look",  // 53: Psyduck
    "often|seen|swim|ming|elegantly",  // 54: Golduck
    "extremely|quick|anger|could|docile",  // 55: Mankey
    "always|furious|tenacious|boot|abandon",  // 56: Primeape
    "protective|territory|bark|bite|repel",  // 57: Growlithe
    "admired|since|past|beauty|runs",  // 58: Arcanine
    "newly|grown|legs|prevent|running",  // 59: Poliwag
    "capable|living|water|sweats|keep",  // 60: Poliwhirl
    "adept|swimmer|both|front|crawl",  // 61: Poliwrath
    "using|ability|read|minds|identify",  // 62: Abra
    "emits|special|alpha|waves|body",  // 63: Kadabra
    "brain|perform|super|computer|intelligence",  // 64: Alakazam
    "loves|build|muscles|trains|styles",  // 65: Machop
    "muscular|body|powerful|must|wear",  // 66: Machoke
    "using|heavy|muscles|throws|powerful",  // 67: Machamp
    "carnivorous|traps|eats|bugs|uses",  // 68: Bellsprout
    "spits|poisonpowder|immobilize|enemy|then",  // 69: Weepinbell
    "live|huge|colonies|deep|jungles",  // 70: Victreebel
    "drifts|shallow|seas|anglers|hook",  // 71: Tentacool
    "tentacles|normally|kept|short|hunts",  // 72: Tentacruel
    "found|fields|mountains|mistaking|them",  // 73: Geodude
    "rolls|down|slopes|move|over",  // 74: Graveler
    "boulder|like|body|extremely|hard",  // 75: Golem
    "hooves|times|harder|diamonds|trample",  // 76: Ponyta
    "competitive|chase|anything|moves|fast",  // 77: Rapidash
    "incredibly|slow|dopey|takes|seconds",  // 78: Slowpoke
    "shellder|latched|onto|slowpoke|tail",  // 79: Slowbro
    "uses|anti|gravity|stay|suspended",  // 80: Magnemite
    "formed|several|magnemites|linked|together",  // 81: Magneton
    "sprig|green|onions|holds|weapon",  // 82: Farfetch'd
    "bird|makes|poor|flying|fast",  // 83: Doduo
    "uses|three|brains|execute|complex",  // 84: Dodrio
    "protruding|horn|head|hard|used",  // 85: Seel
    "stores|thermal|energy|body|swims",  // 86: Dewgong
    "appears|filthy|areas|thrives|sucking",  // 87: Grimer
    "thickly|covered|filthy|vile|sludge",  // 88: Muk
    "hard|shell|repels|kind|attack",  // 89: Shellder
    "attacked|launches|horns|quick|volleys",  // 90: Cloyster
    "almost|invisible|gaseous|cloaks|target",  // 91: Gastly
    "because|ability|slip|through|block",  // 92: Haunter
    "under|full|moon|likes|mimic",  // 93: Gengar
    "grows|stone|portions|body|harden",  // 94: Onix
    "puts|enemies|sleep|then|eats",  // 95: Drowzee
    "locks|eyes|enemy|moves|such",  // 96: Hypno
    "pincers|only|powerful|weapons|used",  // 97: Krabby
    "large|pincer|crushing|power|however",  // 98: Kingler
    "usually|found|power|plants|easily",  // 99: Voltorb
    "stores|electric|energy|under|high",  // 100: Electrode
    "often|mistaken|eggs|disturbed|quickly",  // 101: Exeggcute
    "legend|rare|occasions|heads|drop",  // 102: Exeggutor
    "because|never|removes|skull|helmet",  // 103: Cubone
    "bone|holds|weapon|throws|skillfully",  // 104: Marowak
    "hurry|legs|lengthen|progressively|runs",  // 105: Hitmonlee
    "while|apparently|doing|nothing|fires",  // 106: Hitmonchan
    "tongue|extended|like|chameleon|leaves",  // 107: Lickitung
    "because|stores|several|kinds|toxic",  // 108: Koffing
    "where|kinds|poison|gases|meet",  // 109: Weezing
    "massive|bones|times|harder|human",  // 110: Rhyhorn
    "protected|armor|like|hide|capable",  // 111: Rhydon
    "rare|elusive|bring|happiness|those",  // 112: Chansey
    "whole|body|swathed|wide|vines",  // 113: Tangela
    "infant|rarely|ventures|mother|protective",  // 114: Kangaskhan
    "known|shoot|down|flying|bugs",  // 115: Horsea
    "capable|swim|ming|backwards|rapidly",  // 116: Seadra
    "tail|billows|like|elegant|ballroom",  // 117: Goldeen
    "autumn|spawning|season|seen|swimming",  // 118: Seaking
    "enigmatic|effortlessly|regenerate|appendage|loses",  // 119: Staryu
    "central|core|glows|seven|colors",  // 120: Starmie
    "interrupted|while|miming|slap|around",  // 121: Mr. Mime
    "ninja|like|agility|speed|create",  // 122: Scyther
    "seductively|wiggles|hips|walks|cause",  // 123: Jynx
    "normally|found|near|power|plants",  // 124: Electabuzz
    "body|always|burns|orange|glow",  // 125: Magmar
    "fails|crush|victim|pincers|swing",  // 126: Pinsir
    "targets|enemy|charges|furiously|while",  // 127: Tauros
    "distant|past|somewhat|stronger|horribly",  // 128: Magikarp
    "rarely|seen|wild|huge|vicious",  // 129: Gyarados
    "over|hunted|almost|extinction|ferry",  // 130: Lapras
    "capable|copying|enemy|genetic|code",  // 131: Ditto
    "genetic|code|irregular|mutate|exposed",  // 132: Eevee
    "lives|close|water|long|tail",  // 133: Vaporeon
    "accumulates|negative|ions|atmosphere|blast",  // 134: Jolteon
    "storing|thermal|energy|body|temperature",  // 135: Flareon
    "consists|entirely|programming|code|capable",  // 136: Porygon
    "although|long|extinct|rare|cases",  // 137: Omanyte
    "prehistoric|died|heavy|shell|made",  // 138: Omastar
    "resurrected|fossil|found|what|once",  // 139: Kabuto
    "sleek|shape|perfect|swim|ming",  // 140: Kabutops
    "ferocious|historic|goes|enemy|throat",  // 141: Aerodactyl
    "lazy|just|eats|sleeps|rotund",  // 142: Snorlax
    "legendary|bird|appear|doomed|people",  // 143: Articuno
    "legendary|bird|appear|clouds|while",  // 144: Zapdos
    "known|legendary|bird|fire|every",  // 145: Moltres
    "long|considered|mythical|until|recently",  // 146: Dratini
    "mystical|exudes|gentle|aura|ability",  // 147: Dragonair
    "extremely|rarely|seen|marine|intelligence",  // 148: Dragonite
    "created|scientist|after|years|horrific",  // 149: Mewtwo
    "rare|still|mirage|many|experts",  // 150: Mew
};

// ── Species profiles (Pokedex order 1-151) ─────────────────────────────
static const DaycareSpecies daycareSpecies[] = {
    // [  1] Bulbasaur
    {1, 10, 3, 2, 3, PERS_GENTLE, 0, 15, {33, 45, 73, 22, 77, 75, 74, 79, 76, 14, 15, 34, 36, 38, 72}, 0},
    // [  2] Ivysaur
    {2, 10, 3, 2, 3, PERS_ANXIOUS, 1, 15, {33, 45, 73, 22, 77, 75, 74, 79, 76, 14, 15, 34, 36, 38, 72}, 1},
    // [  3] Venusaur
    {3, 10, 3, 2, 3, PERS_GENTLE, 2, 15, {22, 33, 45, 73, 77, 75, 74, 79, 76, 14, 15, 34, 36, 38, 63}, 2},
    // [  4] Charmander
    {4, 8, 8, 3, 4, PERS_ANXIOUS, 0, 15, {10, 45, 52, 43, 99, 163, 53, 83, 5, 14, 15, 25, 34, 36, 38}, 3},
    // [  5] Charmeleon
    {5, 8, 8, 3, 3, PERS_AGGRESSIVE, 1, 15, {10, 45, 52, 43, 99, 163, 53, 83, 5, 14, 15, 25, 34, 36, 38}, 4},
    // [  6] Charizard
    {6, 8, 2, 3, 3, PERS_PROUD, 2, 15, {10, 43, 45, 52, 99, 163, 53, 83, 5, 14, 15, 25, 34, 36, 38}, 5},
    // [  7] Squirtle
    {7, 9, 9, 8, 2, PERS_SNEAKY, 0, 15, {33, 39, 145, 55, 44, 110, 130, 56, 5, 25, 34, 36, 38, 57, 58}, 6},
    // [  8] Wartortle
    {8, 9, 9, 8, 2, PERS_PROUD, 1, 15, {33, 39, 145, 55, 44, 110, 130, 56, 5, 25, 34, 36, 38, 57, 58}, 7},
    // [  9] Blastoise
    {9, 9, 9, 8, 0, PERS_GENTLE, 2, 15, {33, 39, 55, 145, 44, 110, 130, 56, 5, 25, 34, 36, 38, 57, 58}, 8},
    // [ 10] Caterpie
    {10, 6, 6, 1, 0, PERS_ANXIOUS, 0, 2, {33, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 9},
    // [ 11] Metapod
    {11, 6, 6, 1, 2, PERS_LAZY, 1, 1, {106, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 10},
    // [ 12] Butterfree
    {12, 6, 2, 1, 3, PERS_GENTLE, 2, 15, {93, 77, 78, 79, 48, 18, 60, 13, 36, 38, 63, 72, 76, 92, 94}, 11},
    // [ 13] Weedle
    {13, 6, 3, 1, 4, PERS_ANXIOUS, 0, 2, {40, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 12},
    // [ 14] Kakuna
    {14, 6, 3, 1, 2, PERS_LAZY, 1, 1, {106, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 13},
    // [ 15] Beedrill
    {15, 6, 3, 1, 1, PERS_AGGRESSIVE, 2, 15, {31, 116, 41, 99, 42, 97, 14, 15, 36, 38, 63, 72, 92, 102, 104}, 14},
    // [ 16] Pidgey
    {16, 0, 2, 1, 4, PERS_GENTLE, 0, 15, {16, 28, 98, 18, 17, 97, 119, 13, 19, 36, 38, 92, 99, 102, 104}, 15},
    // [ 17] Pidgeotto
    {17, 0, 2, 1, 4, PERS_PROUD, 1, 15, {16, 28, 98, 18, 17, 97, 119, 13, 19, 36, 38, 92, 99, 102, 104}, 16},
    // [ 18] Pidgeot
    {18, 0, 2, 1, 4, PERS_PROUD, 2, 15, {16, 28, 98, 18, 17, 97, 119, 13, 19, 36, 38, 63, 92, 99, 102}, 17},
    // [ 19] Rattata
    {19, 0, 0, 2, 4, PERS_ANXIOUS, 0, 15, {33, 39, 98, 158, 116, 162, 34, 36, 38, 55, 59, 61, 85, 87, 91}, 18},
    // [ 20] Raticate
    {20, 0, 0, 2, 4, PERS_AGGRESSIVE, 1, 15, {33, 39, 98, 158, 116, 162, 34, 36, 38, 55, 58, 59, 61, 63, 85}, 19},
    // [ 21] Spearow
    {21, 0, 2, 5, 4, PERS_AGGRESSIVE, 0, 15, {45, 64, 43, 31, 119, 65, 97, 13, 18, 19, 36, 38, 92, 99, 102}, 20},
    // [ 22] Fearow
    {22, 0, 2, 5, 4, PERS_AGGRESSIVE, 1, 15, {43, 45, 64, 31, 119, 65, 97, 13, 18, 19, 36, 38, 63, 92, 99}, 21},
    // [ 23] Ekans
    {23, 3, 3, 2, 1, PERS_SNEAKY, 0, 15, {35, 43, 40, 44, 137, 103, 51, 34, 36, 38, 70, 72, 89, 90, 91}, 22},
    // [ 24] Arbok
    {24, 3, 3, 2, 1, PERS_SNEAKY, 1, 15, {35, 40, 43, 44, 137, 103, 51, 34, 36, 38, 63, 70, 72, 89, 90}, 23},
    // [ 25] Pikachu
    {25, 11, 11, 1, 4, PERS_ANXIOUS, 1, 15, {45, 84, 86, 98, 129, 97, 87, 5, 6, 25, 34, 36, 38, 57, 66}, 24},
    // [ 26] Raichu
    {26, 11, 11, 1, 4, PERS_LAZY, 2, 15, {45, 84, 86, 5, 6, 25, 34, 36, 38, 63, 66, 69, 85, 87, 92}, 25},
    // [ 27] Sandshrew
    {27, 4, 4, 5, 2, PERS_ANXIOUS, 0, 15, {10, 28, 163, 40, 129, 154, 14, 15, 34, 36, 38, 66, 69, 70, 89}, 26},
    // [ 28] Sandslash
    {28, 4, 4, 5, 2, PERS_PROUD, 1, 15, {10, 28, 163, 40, 129, 154, 14, 15, 34, 36, 38, 63, 66, 69, 70}, 27},
    // [ 29] Nidoran F
    {29, 3, 3, 2, 0, PERS_GENTLE, 0, 15, {33, 45, 10, 40, 39, 44, 154, 24, 34, 36, 38, 59, 85, 87, 92}, 28},
    // [ 30] Nidorina
    {30, 3, 3, 2, 0, PERS_GENTLE, 1, 15, {10, 33, 45, 40, 39, 44, 154, 24, 32, 34, 36, 38, 55, 58, 59}, 29},
    // [ 31] Nidoqueen
    {31, 3, 4, 2, 1, PERS_AGGRESSIVE, 2, 15, {10, 33, 34, 39, 40, 5, 6, 25, 32, 36, 38, 55, 57, 58, 59}, 30},
    // [ 32] Nidoran M
    {32, 3, 3, 2, 1, PERS_AGGRESSIVE, 0, 15, {33, 43, 30, 40, 116, 31, 32, 24, 34, 36, 38, 59, 85, 87, 92}, 31},
    // [ 33] Nidorino
    {33, 3, 3, 2, 1, PERS_AGGRESSIVE, 1, 15, {30, 33, 43, 40, 116, 31, 32, 24, 34, 36, 38, 55, 58, 59, 61}, 32},
    // [ 34] Nidoking
    {34, 3, 4, 2, 1, PERS_PROUD, 2, 15, {30, 33, 37, 40, 5, 6, 25, 32, 34, 36, 38, 55, 57, 58, 59}, 33},
    // [ 35] Clefairy
    {35, 0, 0, 3, 0, PERS_ANXIOUS, 1, 15, {1, 45, 47, 3, 107, 118, 111, 113, 5, 25, 34, 36, 38, 55, 58}, 34},
    // [ 36] Clefable
    {36, 0, 0, 3, 0, PERS_GENTLE, 2, 15, {3, 47, 107, 118, 5, 25, 34, 36, 38, 55, 58, 59, 61, 63, 66}, 35},
    // [ 37] Vulpix
    {37, 8, 8, 2, 0, PERS_PROUD, 0, 15, {39, 52, 98, 46, 109, 53, 83, 34, 36, 38, 91, 92, 99, 102, 104}, 36},
    // [ 38] Ninetales
    {38, 8, 8, 2, 0, PERS_PROUD, 1, 15, {39, 46, 52, 98, 34, 36, 38, 63, 91, 92, 99, 102, 104, 115, 117}, 37},
    // [ 39] Jigglypuff
    {39, 0, 0, 2, 0, PERS_PROUD, 1, 15, {47, 1, 50, 111, 3, 156, 34, 38, 5, 25, 36, 55, 58, 59, 61}, 38},
    // [ 40] Wigglytuff
    {40, 0, 0, 2, 0, PERS_GENTLE, 2, 15, {3, 47, 50, 111, 5, 25, 34, 36, 38, 55, 58, 59, 61, 63, 66}, 39},
    // [ 41] Zubat
    {41, 3, 2, 0, 4, PERS_SNEAKY, 0, 15, {141, 48, 44, 109, 17, 114, 13, 18, 36, 38, 72, 92, 99, 102, 104}, 40},
    // [ 42] Golbat
    {42, 3, 2, 0, 4, PERS_SNEAKY, 1, 15, {44, 103, 141, 48, 109, 17, 114, 13, 18, 36, 38, 63, 72, 92, 99}, 41},
    // [ 43] Oddish
    {43, 10, 3, 2, 3, PERS_ANXIOUS, 0, 15, {71, 77, 78, 79, 51, 80, 76, 14, 15, 36, 38, 72, 92, 99, 102}, 42},
    // [ 44] Gloom
    {44, 10, 3, 2, 3, PERS_LAZY, 1, 15, {71, 77, 78, 79, 51, 80, 76, 14, 15, 36, 38, 72, 92, 99, 102}, 43},
    // [ 45] Vileplume
    {45, 10, 3, 2, 3, PERS_GENTLE, 2, 15, {51, 78, 79, 80, 77, 14, 15, 34, 36, 38, 63, 72, 76, 92, 99}, 44},
    // [ 46] Paras
    {46, 6, 10, 1, 1, PERS_ANXIOUS, 0, 15, {10, 78, 141, 147, 163, 74, 14, 15, 34, 36, 38, 72, 76, 91, 92}, 45},
    // [ 47] Parasect
    {47, 6, 10, 1, 1, PERS_LAZY, 1, 15, {10, 78, 141, 147, 163, 74, 14, 15, 34, 36, 38, 63, 72, 76, 91}, 46},
    // [ 48] Venonat
    {48, 6, 3, 1, 0, PERS_ANXIOUS, 0, 15, {33, 50, 77, 141, 78, 60, 79, 94, 36, 38, 72, 76, 92, 99, 102}, 47},
    // [ 49] Venomoth
    {49, 6, 3, 1, 3, PERS_SNEAKY, 1, 15, {33, 50, 77, 141, 78, 60, 79, 94, 13, 18, 36, 38, 63, 72, 76}, 48},
    // [ 50] Diglett
    {50, 4, 4, 0, 4, PERS_SNEAKY, 0, 15, {10, 45, 91, 28, 163, 89, 34, 36, 38, 90, 92, 99, 102, 104, 117}, 49},
    // [ 51] Dugtrio
    {51, 4, 4, 0, 4, PERS_SNEAKY, 1, 15, {10, 45, 91, 28, 163, 89, 34, 36, 38, 63, 90, 92, 99, 102, 104}, 50},
    // [ 52] Meowth
    {52, 0, 0, 7, 4, PERS_SNEAKY, 0, 15, {10, 45, 44, 6, 103, 154, 163, 34, 36, 38, 55, 61, 85, 87, 92}, 51},
    // [ 53] Persian
    {53, 0, 0, 7, 4, PERS_PROUD, 1, 15, {10, 44, 45, 103, 6, 154, 163, 34, 36, 38, 55, 61, 63, 85, 87}, 52},
    // [ 54] Psyduck
    {54, 9, 9, 8, 3, PERS_CLUMSY, 0, 15, {10, 39, 50, 93, 154, 56, 5, 6, 25, 34, 36, 38, 55, 57, 58}, 53},
    // [ 55] Golduck
    {55, 9, 9, 8, 3, PERS_PROUD, 1, 15, {10, 39, 50, 93, 154, 56, 5, 6, 25, 34, 36, 38, 55, 57, 58}, 54},
    // [ 56] Mankey
    {56, 1, 1, 3, 1, PERS_AGGRESSIVE, 0, 15, {10, 43, 2, 154, 116, 69, 37, 5, 6, 25, 34, 36, 38, 66, 68}, 55},
    // [ 57] Primeape
    {57, 1, 1, 3, 1, PERS_AGGRESSIVE, 1, 15, {2, 10, 43, 154, 116, 69, 37, 5, 6, 25, 34, 36, 38, 63, 66}, 56},
    // [ 58] Growlithe
    {58, 8, 8, 2, 1, PERS_GENTLE, 0, 15, {44, 46, 52, 43, 36, 97, 53, 34, 38, 82, 91, 92, 99, 102, 104}, 57},
    // [ 59] Arcanine
    {59, 8, 8, 2, 1, PERS_PROUD, 1, 15, {36, 43, 46, 52, 34, 38, 63, 82, 91, 92, 99, 100, 102, 104, 115}, 58},
    // [ 60] Poliwag
    {60, 9, 9, 8, 4, PERS_ANXIOUS, 0, 15, {145, 95, 55, 3, 34, 133, 56, 36, 38, 57, 58, 59, 61, 92, 94}, 59},
    // [ 61] Poliwhirl
    {61, 9, 9, 8, 4, PERS_GENTLE, 1, 15, {55, 95, 145, 3, 34, 133, 56, 5, 25, 36, 38, 57, 58, 59, 61}, 60},
    // [ 62] Poliwrath
    {62, 9, 1, 8, 1, PERS_AGGRESSIVE, 2, 15, {3, 34, 55, 95, 5, 25, 36, 38, 57, 58, 59, 61, 63, 66, 68}, 61},
    // [ 63] Abra
    {63, 12, 12, 7, 3, PERS_SNEAKY, 0, 15, {100, 5, 25, 34, 36, 38, 66, 68, 69, 86, 92, 94, 99, 102, 104}, 62},
    // [ 64] Kadabra
    {64, 12, 12, 7, 3, PERS_SNEAKY, 1, 15, {50, 93, 100, 60, 105, 94, 115, 5, 25, 34, 36, 38, 66, 68, 69}, 63},
    // [ 65] Alakazam
    {65, 12, 12, 7, 3, PERS_PROUD, 2, 15, {50, 93, 100, 60, 105, 94, 115, 5, 25, 34, 36, 38, 63, 66, 68}, 64},
    // [ 66] Machop
    {66, 1, 1, 3, 1, PERS_AGGRESSIVE, 0, 15, {2, 67, 43, 116, 69, 66, 5, 25, 34, 36, 38, 68, 70, 89, 90}, 65},
    // [ 67] Machoke
    {67, 1, 1, 3, 1, PERS_AGGRESSIVE, 1, 15, {2, 43, 67, 116, 69, 66, 5, 25, 34, 36, 38, 68, 70, 89, 90}, 66},
    // [ 68] Machamp
    {68, 1, 1, 3, 1, PERS_AGGRESSIVE, 2, 15, {2, 43, 67, 116, 69, 66, 5, 25, 34, 36, 38, 63, 68, 70, 89}, 67},
    // [ 69] Bellsprout
    {69, 10, 3, 1, 1, PERS_ANXIOUS, 0, 15, {22, 74, 35, 77, 79, 78, 51, 75, 21, 14, 15, 36, 38, 72, 76}, 68},
    // [ 70] Weepinbell
    {70, 10, 3, 1, 1, PERS_AGGRESSIVE, 1, 15, {22, 35, 74, 77, 79, 78, 51, 75, 21, 14, 15, 36, 38, 72, 76}, 69},
    // [ 71] Victreebel
    {71, 10, 3, 1, 1, PERS_AGGRESSIVE, 2, 15, {51, 75, 78, 79, 35, 77, 14, 15, 34, 36, 38, 63, 72, 76, 92}, 70},
    // [ 72] Tentacool
    {72, 9, 3, 6, 0, PERS_ANXIOUS, 0, 15, {51, 48, 35, 40, 55, 132, 112, 103, 56, 14, 15, 36, 38, 57, 58}, 71},
    // [ 73] Tentacruel
    {73, 9, 3, 6, 0, PERS_AGGRESSIVE, 1, 15, {35, 48, 51, 40, 55, 132, 112, 103, 56, 14, 15, 36, 38, 57, 58}, 72},
    // [ 74] Geodude
    {74, 5, 4, 3, 2, PERS_AGGRESSIVE, 0, 15, {33, 111, 88, 120, 106, 89, 153, 5, 34, 36, 38, 66, 68, 69, 70}, 73},
    // [ 75] Graveler
    {75, 5, 4, 3, 2, PERS_AGGRESSIVE, 1, 15, {33, 111, 88, 120, 106, 89, 153, 5, 34, 36, 38, 66, 68, 69, 70}, 74},
    // [ 76] Golem
    {76, 5, 4, 3, 2, PERS_AGGRESSIVE, 2, 15, {33, 111, 88, 120, 106, 89, 153, 5, 25, 34, 36, 38, 63, 66, 68}, 75},
    // [ 77] Ponyta
    {77, 8, 8, 2, 4, PERS_ANXIOUS, 0, 15, {52, 39, 23, 45, 83, 36, 97, 32, 34, 38, 92, 99, 102, 104, 115}, 76},
    // [ 78] Rapidash
    {78, 8, 8, 2, 4, PERS_PROUD, 1, 15, {23, 39, 45, 52, 83, 36, 97, 32, 34, 38, 63, 92, 99, 102, 104}, 77},
    // [ 79] Slowpoke
    {79, 9, 12, 8, 0, PERS_CLUMSY, 0, 15, {93, 50, 29, 45, 55, 133, 94, 6, 34, 36, 38, 57, 58, 59, 61}, 78},
    // [ 80] Slowbro
    {80, 9, 12, 8, 2, PERS_LAZY, 1, 15, {29, 50, 93, 45, 55, 110, 133, 94, 5, 6, 25, 34, 36, 38, 57}, 79},
    // [ 81] Magnemite
    {81, 11, 11, 5, 3, PERS_ANXIOUS, 0, 15, {33, 49, 84, 48, 86, 129, 103, 36, 38, 85, 87, 92, 99, 100, 102}, 80},
    // [ 82] Magneton
    {82, 11, 11, 5, 3, PERS_PROUD, 1, 15, {33, 49, 84, 48, 86, 129, 103, 36, 38, 63, 85, 87, 92, 99, 100}, 81},
    // [ 83] Farfetch'd
    {83, 0, 2, 2, 1, PERS_CLUMSY, 0, 15, {28, 64, 43, 31, 14, 97, 163, 13, 15, 18, 19, 34, 36, 38, 92}, 82},
    // [ 84] Doduo
    {84, 0, 2, 2, 1, PERS_CLUMSY, 0, 15, {64, 45, 31, 65, 99, 161, 97, 18, 19, 34, 36, 38, 92, 102, 104}, 83},
    // [ 85] Dodrio
    {85, 0, 2, 2, 1, PERS_AGGRESSIVE, 1, 15, {31, 45, 64, 65, 99, 161, 97, 18, 19, 34, 36, 38, 63, 92, 102}, 84},
    // [ 86] Seel
    {86, 9, 9, 6, 0, PERS_GENTLE, 0, 15, {29, 45, 62, 156, 36, 58, 6, 32, 34, 38, 55, 57, 59, 61, 70}, 85},
    // [ 87] Dewgong
    {87, 9, 13, 6, 0, PERS_GENTLE, 1, 15, {29, 45, 62, 156, 36, 58, 6, 32, 34, 38, 55, 57, 59, 61, 63}, 86},
    // [ 88] Grimer
    {88, 3, 3, 7, 0, PERS_GENTLE, 0, 15, {1, 50, 139, 107, 124, 106, 103, 151, 34, 72, 85, 87, 92, 99, 102}, 87},
    // [ 89] Muk
    {89, 3, 3, 7, 0, PERS_GENTLE, 1, 15, {1, 50, 139, 107, 124, 106, 103, 151, 34, 63, 72, 85, 87, 92, 99}, 88},
    // [ 90] Shellder
    {90, 9, 9, 6, 2, PERS_ANXIOUS, 0, 15, {33, 110, 48, 128, 62, 43, 58, 36, 38, 55, 57, 59, 61, 92, 99}, 89},
    // [ 91] Cloyster
    {91, 9, 13, 6, 2, PERS_PROUD, 1, 15, {48, 62, 110, 128, 131, 36, 38, 55, 57, 58, 59, 61, 63, 92, 99}, 90},
    // [ 92] Gastly
    {92, 7, 3, 0, 3, PERS_SNEAKY, 0, 15, {101, 109, 122, 95, 138, 72, 85, 87, 92, 94, 99, 102, 104, 117, 120}, 91},
    // [ 93] Haunter
    {93, 7, 3, 0, 3, PERS_SNEAKY, 1, 15, {101, 109, 122, 95, 138, 72, 85, 87, 92, 94, 99, 102, 104, 117, 120}, 92},
    // [ 94] Gengar
    {94, 7, 3, 0, 3, PERS_SNEAKY, 2, 15, {101, 109, 122, 95, 138, 5, 25, 34, 36, 38, 63, 66, 68, 69, 70}, 93},
    // [ 95] Onix
    {95, 5, 4, 0, 2, PERS_PROUD, 0, 15, {33, 103, 20, 88, 99, 21, 106, 34, 36, 38, 70, 89, 90, 91, 92}, 94},
    // [ 96] Drowzee
    {96, 12, 12, 2, 0, PERS_SNEAKY, 0, 15, {1, 95, 50, 93, 29, 139, 94, 96, 5, 25, 34, 36, 38, 66, 68}, 95},
    // [ 97] Hypno
    {97, 12, 12, 2, 0, PERS_SNEAKY, 1, 15, {1, 50, 93, 95, 29, 139, 94, 96, 5, 25, 34, 36, 38, 63, 66}, 96},
    // [ 98] Krabby
    {98, 9, 9, 8, 1, PERS_AGGRESSIVE, 0, 15, {43, 145, 11, 12, 23, 152, 106, 14, 15, 34, 36, 38, 55, 57, 58}, 97},
    // [ 99] Kingler
    {99, 9, 9, 8, 1, PERS_AGGRESSIVE, 1, 15, {11, 43, 145, 12, 23, 152, 106, 14, 15, 34, 36, 38, 55, 57, 58}, 98},
    // [100] Voltorb
    {100, 11, 11, 7, 4, PERS_AGGRESSIVE, 0, 15, {33, 103, 49, 120, 113, 129, 153, 36, 85, 86, 87, 92, 99, 100, 102}, 99},
    // [101] Electrode
    {101, 11, 11, 7, 4, PERS_AGGRESSIVE, 1, 15, {33, 49, 103, 120, 113, 129, 153, 36, 63, 85, 86, 87, 92, 99, 100}, 100},
    // [102] Exeggcute
    {102, 10, 12, 1, 2, PERS_ANXIOUS, 0, 15, {95, 140, 115, 73, 78, 77, 76, 79, 36, 38, 92, 94, 99, 100, 102}, 101},
    // [103] Exeggutor
    {103, 10, 12, 1, 3, PERS_LAZY, 1, 15, {95, 140, 23, 36, 38, 63, 70, 72, 76, 92, 94, 99, 100, 102, 104}, 102},
    // [104] Cubone
    {104, 4, 4, 3, 2, PERS_ANXIOUS, 0, 15, {45, 125, 43, 116, 37, 155, 99, 5, 25, 34, 36, 38, 55, 58, 59}, 103},
    // [105] Marowak
    {105, 4, 4, 3, 2, PERS_PROUD, 1, 15, {43, 45, 116, 125, 37, 155, 99, 5, 25, 34, 36, 38, 55, 58, 59}, 104},
    // [106] Hitmonlee
    {106, 1, 1, 7, 1, PERS_AGGRESSIVE, 1, 15, {24, 96, 27, 26, 116, 136, 25, 5, 34, 36, 38, 66, 68, 69, 70}, 105},
    // [107] Hitmonchan
    {107, 1, 1, 7, 0, PERS_AGGRESSIVE, 1, 15, {4, 97, 7, 8, 9, 5, 68, 25, 34, 36, 38, 66, 69, 70, 92}, 106},
    // [108] Lickitung
    {108, 0, 0, 2, 0, PERS_CLUMSY, 0, 15, {35, 48, 23, 50, 111, 21, 103, 5, 14, 15, 25, 34, 36, 38, 55}, 107},
    // [109] Koffing
    {109, 3, 3, 7, 2, PERS_GENTLE, 0, 15, {33, 123, 124, 108, 120, 114, 153, 85, 87, 92, 99, 102, 104, 117, 126}, 108},
    // [110] Weezing
    {110, 3, 3, 7, 2, PERS_LAZY, 1, 15, {33, 123, 124, 108, 120, 114, 153, 63, 85, 87, 92, 99, 102, 104, 117}, 109},
    // [111] Rhyhorn
    {111, 4, 5, 5, 2, PERS_AGGRESSIVE, 0, 15, {30, 23, 39, 31, 32, 43, 36, 34, 38, 70, 85, 87, 89, 90, 91}, 110},
    // [112] Rhydon
    {112, 4, 5, 5, 1, PERS_AGGRESSIVE, 1, 15, {23, 30, 31, 39, 32, 43, 36, 5, 6, 25, 34, 38, 55, 57, 58}, 111},
    // [113] Chansey
    {113, 0, 0, 7, 0, PERS_GENTLE, 1, 15, {1, 3, 47, 45, 107, 111, 113, 38, 5, 25, 34, 36, 55, 58, 59}, 112},
    // [114] Tangela
    {114, 10, 10, 2, 2, PERS_ANXIOUS, 0, 15, {20, 132, 71, 77, 78, 79, 21, 74, 14, 15, 34, 36, 38, 63, 72}, 113},
    // [115] Kangaskhan
    {115, 0, 0, 2, 0, PERS_GENTLE, 0, 15, {4, 99, 44, 39, 5, 43, 146, 25, 34, 36, 38, 55, 57, 58, 59}, 114},
    // [116] Horsea
    {116, 9, 9, 6, 2, PERS_ANXIOUS, 0, 15, {145, 108, 43, 55, 97, 56, 36, 38, 57, 58, 59, 61, 92, 99, 102}, 115},
    // [117] Seadra
    {117, 9, 9, 6, 2, PERS_PROUD, 1, 15, {108, 145, 43, 55, 97, 56, 36, 38, 57, 58, 59, 61, 63, 92, 99}, 116},
    // [118] Goldeen
    {118, 9, 9, 8, 1, PERS_PROUD, 0, 15, {39, 64, 48, 30, 31, 127, 32, 97, 36, 38, 55, 57, 58, 59, 61}, 117},
    // [119] Seaking
    {119, 9, 9, 8, 1, PERS_PROUD, 1, 15, {39, 48, 64, 30, 31, 127, 32, 97, 36, 38, 55, 57, 58, 59, 61}, 118},
    // [120] Staryu
    {120, 9, 9, 6, 4, PERS_ANXIOUS, 0, 15, {33, 55, 106, 105, 129, 107, 113, 56, 36, 38, 57, 58, 59, 61, 85}, 119},
    // [121] Starmie
    {121, 9, 12, 6, 4, PERS_PROUD, 1, 15, {33, 55, 106, 36, 38, 57, 58, 59, 61, 63, 85, 86, 87, 92, 94}, 120},
    // [122] Mr. Mime
    {122, 12, 12, 7, 0, PERS_SNEAKY, 1, 15, {93, 112, 113, 3, 96, 164, 5, 25, 34, 36, 38, 63, 66, 68, 69}, 121},
    // [123] Scyther
    {123, 6, 2, 2, 1, PERS_AGGRESSIVE, 0, 15, {98, 43, 116, 104, 163, 14, 97, 15, 36, 38, 63, 92, 99, 102, 117}, 122},
    // [124] Jynx
    {124, 13, 12, 7, 3, PERS_PROUD, 1, 15, {1, 142, 122, 3, 8, 34, 37, 59, 5, 25, 36, 38, 55, 58, 61}, 123},
    // [125] Electabuzz
    {125, 11, 11, 2, 4, PERS_AGGRESSIVE, 1, 15, {43, 98, 84, 103, 9, 113, 87, 5, 25, 34, 36, 38, 63, 66, 68}, 124},
    // [126] Magmar
    {126, 8, 8, 3, 3, PERS_AGGRESSIVE, 1, 15, {52, 43, 109, 7, 108, 123, 53, 5, 25, 34, 36, 38, 63, 66, 68}, 125},
    // [127] Pinsir
    {127, 6, 6, 1, 1, PERS_AGGRESSIVE, 0, 15, {11, 69, 12, 116, 106, 163, 14, 15, 34, 36, 38, 63, 66, 70, 92}, 126},
    // [128] Tauros
    {128, 0, 0, 2, 4, PERS_AGGRESSIVE, 0, 15, {33, 23, 39, 43, 99, 36, 32, 34, 38, 58, 59, 63, 70, 85, 87}, 127},
    // [129] Magikarp
    {129, 9, 9, 8, 4, PERS_CLUMSY, 0, 2, {150, 33, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 128},
    // [130] Gyarados
    {130, 9, 2, 8, 1, PERS_PROUD, 1, 15, {43, 44, 56, 82, 63, 34, 36, 38, 55, 57, 58, 59, 61, 70, 85}, 129},
    // [131] Lapras
    {131, 9, 13, 6, 0, PERS_GENTLE, 0, 15, {45, 55, 47, 54, 34, 109, 58, 56, 32, 36, 38, 57, 59, 61, 63}, 130},
    // [132] Ditto
    {132, 0, 0, 7, 0, PERS_SNEAKY, 0, 1, {144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 131},
    // [133] Eevee
    {133, 0, 0, 7, 0, PERS_ANXIOUS, 0, 15, {28, 33, 98, 39, 44, 36, 34, 38, 92, 99, 102, 104, 115, 117, 129}, 132},
    // [134] Vaporeon
    {134, 9, 9, 7, 0, PERS_GENTLE, 1, 15, {28, 33, 55, 98, 39, 44, 151, 114, 54, 56, 34, 36, 38, 57, 58}, 133},
    // [135] Jolteon
    {135, 11, 11, 7, 4, PERS_ANXIOUS, 1, 15, {28, 33, 84, 98, 39, 86, 24, 97, 42, 87, 34, 36, 38, 63, 85}, 134},
    // [136] Flareon
    {136, 8, 8, 7, 1, PERS_LAZY, 1, 15, {28, 33, 52, 98, 39, 44, 43, 83, 99, 53, 34, 36, 38, 63, 92}, 135},
    // [137] Porygon
    {137, 0, 0, 7, 3, PERS_ANXIOUS, 0, 15, {33, 159, 160, 60, 105, 97, 161, 36, 38, 58, 59, 63, 85, 86, 87}, 136},
    // [138] Omanyte
    {138, 5, 9, 6, 2, PERS_ANXIOUS, 0, 15, {55, 110, 30, 43, 131, 56, 34, 36, 38, 57, 58, 59, 61, 92, 99}, 137},
    // [139] Omastar
    {139, 5, 9, 6, 2, PERS_AGGRESSIVE, 1, 15, {30, 55, 110, 43, 131, 56, 32, 34, 36, 38, 57, 58, 59, 61, 63}, 138},
    // [140] Kabuto
    {140, 5, 9, 6, 2, PERS_ANXIOUS, 0, 15, {10, 106, 71, 163, 43, 56, 34, 36, 38, 55, 57, 58, 59, 61, 92}, 139},
    // [141] Kabutops
    {141, 5, 9, 6, 1, PERS_AGGRESSIVE, 1, 15, {10, 71, 106, 163, 43, 56, 13, 14, 25, 34, 36, 38, 55, 57, 58}, 140},
    // [142] Aerodactyl
    {142, 5, 2, 3, 4, PERS_AGGRESSIVE, 0, 15, {17, 97, 48, 44, 36, 63, 13, 18, 19, 38, 82, 92, 99, 102, 104}, 141},
    // [143] Snorlax
    {143, 0, 0, 3, 0, PERS_LAZY, 1, 15, {29, 133, 156, 34, 106, 38, 63, 5, 6, 25, 36, 55, 57, 58, 59}, 142},
    // [144] Articuno
    {144, 13, 2, 4, 0, PERS_PROUD, 0, 15, {58, 64, 59, 97, 54, 13, 18, 19, 36, 38, 55, 61, 63, 92, 99}, 143},
    // [145] Zapdos
    {145, 11, 2, 4, 3, PERS_AGGRESSIVE, 0, 15, {65, 84, 87, 97, 113, 13, 18, 19, 36, 38, 63, 85, 86, 92, 99}, 144},
    // [146] Moltres
    {146, 8, 2, 4, 3, PERS_PROUD, 0, 15, {64, 83, 43, 97, 143, 13, 18, 19, 36, 38, 63, 92, 99, 102, 104}, 145},
    // [147] Dratini
    {147, 14, 14, 8, 1, PERS_ANXIOUS, 0, 15, {35, 43, 86, 97, 21, 82, 63, 34, 36, 38, 55, 57, 58, 59, 61}, 146},
    // [148] Dragonair
    {148, 14, 14, 8, 1, PERS_PROUD, 1, 15, {35, 43, 86, 97, 21, 82, 63, 32, 34, 36, 38, 55, 57, 58, 59}, 147},
    // [149] Dragonite
    {149, 14, 2, 8, 1, PERS_PROUD, 2, 15, {35, 43, 86, 97, 21, 82, 63, 13, 32, 34, 36, 38, 55, 57, 58}, 148},
    // [150] Mewtwo
    {150, 12, 12, 4, 3, PERS_AGGRESSIVE, 0, 15, {50, 93, 94, 129, 112, 105, 54, 133, 5, 6, 25, 34, 36, 38, 55}, 149},
    // [151] Mew
    {151, 12, 12, 4, 0, PERS_SNEAKY, 0, 15, {1, 144, 5, 118, 94, 6, 13, 14, 15, 18, 19, 25, 32, 34, 36}, 150},
};
static constexpr uint8_t DAYCARE_SPECIES_COUNT = 151;

// ── Type behavior weights ─────────────────────────────────────────────────
// { social, combat, explore, rest, mischief }
struct TypeBehavior {
    uint8_t social, combat, explore, rest, mischief;
};

static const TypeBehavior daycareTypeBehaviors[TYPE_COUNT] = {
    {200,  80, 120, 180,  60},  // normal
    {120, 255,  80,  60,  40},  // fighting
    {140, 100, 200, 100,  80},  // flying
    { 60, 100, 100, 120, 200},  // poison
    { 80, 120, 180, 160,  40},  // ground
    { 60, 140, 120, 200,  20},  // rock
    {100, 100, 180, 120,  80},  // bug
    { 40, 100, 120,  80, 255},  // ghost
    {100, 200, 120, 140, 100},  // fire
    {160, 100, 180, 120,  80},  // water
    {160,  60, 140, 200,  40},  // grass
    {120, 140, 160,  60, 200},  // electric
    { 80, 100, 100, 160, 120},  // psychic
    {100,  80, 120, 180,  60},  // ice
    { 60, 200, 140, 100,  60},  // dragon
};

// ── Dex number -> species table index (1-based, 0 = invalid) ───────────
inline const DaycareSpecies *daycareGetSpecies(uint8_t dexNum) {
    if (dexNum < 1 || dexNum > DAYCARE_SPECIES_COUNT) return nullptr;
    return &daycareSpecies[dexNum - 1];
}

