// SPDX-License-Identifier: MIT
//
// Auto-generated by scripts/gen_gen3_data.py -- DO NOT EDIT BY HAND.
//
// Gen 2/3-mechanics battle data (Special split, Dark/Steel, modern type chart
// and move typings). Physical/special is still decided by TYPE (Gen 4 made it
// per-move). Source: Pokemon Showdown data (MIT), Smogon University.
// Pokemon and all related marks are trademarks of Nintendo / Game Freak /
// Creatures -- this file contains only mechanical/statistical data.
//
#pragma once
#include <stdint.h>


static constexpr const char *GEN3_TYPE_NAMES[] = {
    "NORMAL",
    "FIGHTING",
    "FLYING",
    "POISON",
    "GROUND",
    "ROCK",
    "BIRD",
    "BUG",
    "GHOST",
    "FIRE",
    "WATER",
    "GRASS",
    "ELECTRIC",
    "PSYCHIC",
    "ICE",
    "DRAGON",
    "DARK",
    "STEEL",
};
static constexpr uint8_t GEN3_TYPE_COUNT = 18;

// Physical/special is by ATTACK TYPE in Gen 2/3 (true = special).
static constexpr uint8_t GEN3_TYPE_IS_SPECIAL[18] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0 };

// GEN3_TYPECHART[attackerType][defenderType]:
// 0 = immune, 1 = resist (0.5x), 2 = neutral (1x), 4 = super (2x).
static constexpr uint8_t GEN3_TYPECHART[18][18] = {
    { 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1 },  // normal
    { 4, 2, 1, 1, 2, 4, 2, 1, 0, 2, 2, 2, 2, 1, 4, 2, 4, 4 },  // fighting
    { 2, 4, 2, 2, 2, 1, 2, 4, 2, 2, 2, 4, 1, 2, 2, 2, 2, 1 },  // flying
    { 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 4, 2, 2, 2, 2, 2, 0 },  // poison
    { 2, 2, 0, 4, 2, 4, 2, 1, 2, 4, 2, 1, 4, 2, 2, 2, 2, 4 },  // ground
    { 2, 1, 4, 2, 1, 2, 2, 4, 2, 4, 2, 2, 2, 2, 4, 2, 2, 1 },  // rock
    { 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2 },  // bird
    { 2, 1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 4, 2, 4, 2, 2, 4, 1 },  // bug
    { 0, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 4, 2, 2, 1, 2 },  // ghost
    { 2, 2, 2, 2, 2, 1, 2, 4, 2, 1, 1, 4, 2, 2, 4, 1, 2, 4 },  // fire
    { 2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 1, 1, 2, 2, 2, 1, 2, 2 },  // water
    { 2, 2, 1, 1, 4, 4, 2, 1, 2, 1, 4, 1, 2, 2, 2, 1, 2, 1 },  // grass
    { 2, 2, 4, 2, 0, 2, 2, 2, 2, 2, 4, 1, 1, 2, 2, 1, 2, 2 },  // electric
    { 2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 1 },  // psychic
    { 2, 2, 4, 2, 4, 2, 2, 2, 2, 1, 1, 4, 2, 2, 1, 4, 2, 1 },  // ice
    { 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 1 },  // dragon
    { 2, 1, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 4, 2, 2, 1, 2 },  // dark
    { 2, 2, 2, 2, 2, 4, 2, 2, 2, 1, 1, 2, 1, 2, 4, 2, 2, 1 },  // steel
};
